---
version: '3.8'
services:
  db:
    image: mariadb
    container_name: mariadb_Senac
    restart: always
    shm_size: 128mb
    volumes:
    - mariadb_volume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"


volumes:
  mariadb_volume:
  # reprografia:
